index.html
js/app.js

Closes #5 
change wording from password to token and update several useful information

Closes #5 Change wording from password to token

---

.github/pull_request_template.md

Fixes #8.  (<=== Add issue number here)
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

Fixes #8: Created PR template

---

js/app.js

Replace all 'var' instances with 'let' in app.js

---

index.html

Fixes #24: Updated link of fork me on github

---

index.html
js/app.js

Add 'Delete all labels' button and allow committing after

---

js/app.js

Remove all defined but unused variables within app.js

---

js/app.js

Update all '==' to '===' in app.js

---

css/colorpicker.css

Merge declarations of duplicate selectors

---

index.html
js/app.js

Fix #37: Clean up cosmetic stuff and fix typos/errors in html and js

---

css/app.css
index.html
js/app.js

Feature: Streamline removing all existing labels and cloning from another repo; UI touch-ups.

---

js/app.js

**Rewrote copy-all-labels algorithm to accommodate any max number of labels per page via GitHub API**

Rewrote copy-all-labels algorithm

---

js/app.js

Fix #42:Remove confirm popup really want to delete this

---

index.html

Fix #6: Changed from 3-column design to 2-column design

---

css/app.css
index.html
js/app.js

I know the UI is ugly, but we'll fix that later, as we will probably write and write a lot of CSS rules. 
Test passed: I was able to add and modify label descriptions.
The current branch did rebase branch `rebasing debug/enable-recover-button-after-delete` minutes ago.

Fix #2: New feature: add label description

---

js/app.js

Pop up alert when there are 0 existing labels

---

index.html
js/app.js

Fix 52: Replace bootstrap w/ material design for bootstrap

---

index.html
js/app.js

Updated input form's UI with material design. 

Fix #55 Improve input form UI. Split own:repo input to separate inputs

---

index.html
js/app.js

Fix #57: Add "I'm owner of repo" checkbox and auto-copy owner to username if checked

---

css/app.css
js/app.js

Revise delete behavior to grey out; UI tweaks

---

index.html

Move How-this-web-app-works and Is-my-personal-access-token-safe cards after Labels card

Fix 61: Move How-works & Access-token cards after Labels card

---

js/app.js

Fix #66: Check label's description when setting action attribute

---

js/app.js

Bugfix update, delete and commit milestone and enable commit after updating label and milestone
There might be a few minor bugs and corner cases that I haven't tested, but I suggest to move forward with this PR and deal with those bugs in the future as we discover them.
3 screenshots of demo operations of dummy labels and milestones:
Thank you for …

Fix #72 & #73 Bugfix update, delete & commit milestones and labels

---

js/app.js

This PR includes:
- Bugfix: enable 'commit button' after copyping labels/milestones from another repo
- Minor updates on non-functionality things

Bugfix enable commit after copy labels/milestones from other repo

---

js/app.js

The bug is explained in Issue #84.

Fix #84 Debug: commit/create milestones copied from other repo

---

js/app.js

Substitute jQuery .parents() for .closest()

---

css/colorpicker.css
js/colorpicker.js

This PR fixes #35. 
The "save" function is actually there all along, but it was carried out by an ambiguous icon button. This PR replaced the ambiguous icon with a 'Save' button.

Fix #35 Replace ambiguous icon with save button to save color

---

js/app.js

Fix milestone update not adding 'uncommitted'

---

js/app.js

Fix #78: Remove 2 unnecessary semicolons

---

js/app.js

Fix #99: Simplify delete-all-and-copy-button mechanism

---

js/app.js

I chose to comment out the line of code instead of deleting it. Part of the code between lines `337` and `370` seems to be redundant. I'll look into this further, but this PR should fix the original issue.

Fix saving color adding extra uncommitted class to parent element

---

.eslintrc.json
.gitignore
package-lock.json
package.json

Fix #107 Initialize npm and add eslint

---

index.html
js/app.js

Fix #91 & #65 Add function query login info & fix username

---

js/app.js

Change 'labels' to singular form in commit modal messages

---

js/app.js
js/colorpicker.js

Maintenance: Fix ESLint errors

---

.github/pull_request_template.md
README.md
package.json

Automatically run eslint when you commit.

Infrastructure: minor updates on readme, workflow, package.json

---

js/app.js

Rename 'action' attribute to '(data)-todo'

---

js/app.js

Fix #130 Bugfix: update, delete, then commit a label fails

---

.eslintrc.js
js/app.js

Fix #132 Fix Eslint no-invalid-this errors by add JSDoc

---

js/app.js

Make input changes monitor all other inputs to determine 'todo'

---

README.md
index.html
package.json

Update organization name and link in all relevant files

---

README.md
index.html

I don't why the git diff has so many changes. I just fixed a few typos and made a few minor updates. 
I think it's a styling thing with Prettier. We'll see if it will keep doing similar things in the future.
Real changes are:
- Github -> GitHub
- repositorys -> repositories
- Badwater-Bay -> BadwaterBay
- Added a few words to 2-3 places. Very minor updates.
> We're happy to help you get this ready. Don't be afraid to ask for help, and **don't be discouraged** if your tests fail …

Typo fixes and other minor text updates

---

README.md
package-lock.json
package.json
src/components/navbar.js
src/index.html

Update new project name and update README text

---

bs-config.js
package.json
src/index.js
yarn.lock

Debug yarn & js script. Now web app works.

---

.github/workflows/nodejs.yml

Remove Node 10.x from CI tests

---

package.json
yarn.lock

Upgrade dependencies: webpack & css-loader

---

src/__tests__/apiCalls.test.js

[ci skip] Minor update: apiCall -> apiCalls in test

---

src/components/loadingModal.js
src/components/loginCard.js
src/js/apiCalls.js
src/js/commitChanges.js
src/js/dataValidation.js

Fire API calls asynchronously in parallel instead of sequentially for:
- Create labels/milestones
- Update...
- Delete...

Fire API calls asynchronously in parallel instead of sequentially

---

README.md
src/app.js
src/components/copyFromCard.js
src/components/loadingModal.js
src/components/loginCard.js
src/components/managementCard.js
src/js/apiCalls.js
src/js/commitChanges.js
src/js/createNewLabelEntry.js
src/js/createNewMilestoneEntry.js
src/js/dataValidation.js
src/js/helpers.js
src/js/manipulateEntries.js

Partially address #97: Display fetched entries in alphabetical order

---

README.md
public/index.html
src/__tests__/dataValidation.test.js
src/__tests__/helpers.test.js
src/__tests__/manipulateEntries.test.js
src/app.js
src/components/managementCard.js
src/index.js
src/js/apiCalls.js
src/js/commitChanges.js
src/js/dataValidation.js
src/js/helpers.js
src/js/manipulateEntries.js
yarn.lock

Sort entries, simplify logic, abstract methods & fix bugs

---

CONTRIBUTING.md
README.md
package.json
public/index.html
src/__tests__/base64.test.js
src/app.js
src/js/dataValidation.js
yarn.lock

Several reasons for the name change: 
- Currently, we're working on making the app a GitHub App, but GitHub does not allow 3rd-party app names that start with "GitHub" or "Gist".
- "Labelcopier" is a lot shorter than "GitHub Label Manager Plus."
- "Labelcopier" reflects the core functionality of the web app.
- "Labelcopier" is similar to "photocopier" and "labelmaker" that people are familiar with.
- No existing repository is named "labelcopier" on GitHub and GitLab.
- No existing GitHub App is named "labelcopier."
- We'd like to extend the app to managing labels and milestones …

Change repo name to Labelcopier from GitHub Label Manager Plus

---

CONTRIBUTING.md
src/app.js
src/index.js
src/wrapper.js
webpack.config.js

Prepare for being a submodule of repo gen1.badwaterbay.com

---

src/app.js
src/components/loginCard.js
src/components/managementCard.js
src/js/apiCalls.js
src/js/commitChanges.js
src/js/dataValidation.js
src/js/loginFormFunctions.js

Users no long need to manually generate a Personal Access Token and copy-paste it into the web app. Now users can click on "Login with GitHub" button to automatically authenticate.
In other words, the web app is now a registered GitHub OAuth app.

Fix #173: Add GitHub OAuth support for authentication

---

src/app.js
src/components/loginCard.js
src/js/apiCalls.js
src/js/commitChanges.js
src/js/dataValidation.js
src/js/loginFormFunctions.js
src/scss/app.scss

Fix #216 Change app from a GitHub OAuth App to a GitHub App

---

.github/dependabot.yml
package.json
yarn.lock

* Minor updates on Dependabot config
* Bump lint-staged from 10.3.0 to 10.5.3
* Bump eslint from 7.8.1 to 7.15.0
* Bump sass from 1.26.10 to 1.30.0
* Bump eslint-config-prettier from 6.11.0 to 7.0.0
* Bump prettier from 2.1.1 to 2.2.1
* Bump @fortawesome/free-solid-svg-icons from 5.14.0 to 5.15.1
* Bump html-webpack-plugin from 4.4.1 to 4.5.0
* Bump eslint-plugin-import from 2.22.0 to 2.22.1
* Bump webpack from 4.44.1 to 4.44.2
> We're happy to help you get this ready. Don't be …

Upgrade dependencies

---

package.json
public/index.html
yarn.lock

:arrow_up: Upgrade dependencies

---

bs-config.js
package.json
yarn.lock

:wrench: Replace Webpack-Cli w/ Browser-Sync

---

package.json
yarn.lock

:wrench: Add webpack-cli back

---

src/js/apiCalls.js

:bug: Fix loading token bug
